[build]
  command = "pip install markdown && python build.py"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.9"

# Explicitly tell Netlify where (not) to look for functions
[functions]
  directory = "no-functions"
