backend:
  name: git-gateway
  branch: main

media_folder: "assets"      # files saved here in your repo
public_folder: "/assets"    # files served here on the site

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/index.md"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "SoftFrequency" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "About" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/pages/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Contact" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}--{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
